### ISSUE TITLE
missing FreiHand_split_ids.json

### ISSUE THREAD

**Issue by cga-cmu** [lijenchang/Mask2Hand#2]
To run either test.py or train.py I seem to need the file FreiHand_split_ids.json

Traceback (most recent call last):
  File "test.py", line 176, in <module>
    test(args)
  File "test.py", line 147, in test
    dataset_frei_test = FreiHandDataset(args.data_path, joints_anno_file, camera_Ks_file, data_split_file, vertices_anno_file, split = 'test', transform = transform, augment = False)
  File "/home/cga/tools/vision/hands/mask2hand/dataset.py", line 97, in __init__
    with open(os.path.join(path, data_split_file), 'r') as fh:
FileNotFoundError: [Errno 2] No such file or directory: './dataset/freihand/FreiHand_split_ids.json'

**Comment by lijenchang** [comment]
Thank you for bringing this to our attention. I've added the download link for this file in the updated README.
